import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  list: Product[] = [{
    "id": 1,
    "catId": "4T1BK1EB4FU499515",
    "name": "Ferrari",
    "description": "599 GTB Fiorano",
    "image": null,
    "price": "$4049.34",
    "stock": 6,
    "featured": true,
    "active": false
  }, {
    "id": 2,
    "catId": "SCFFDABE8BG089891",
    "name": "Mercedes-Benz",
    "description": "CL-Class",
    "image": null,
    "price": "$5914.03",
    "stock": 4,
    "featured": true,
    "active": false
  }, {
    "id": 3,
    "catId": "WBSDE93453C763181",
    "name": "Pontiac",
    "description": "1000",
    "image": null,
    "price": "$4002.02",
    "stock": 1,
    "featured": true,
    "active": true
  }, {
    "id": 4,
    "catId": "WA1BY94L07D382456",
    "name": "Mercedes-Benz",
    "description": "M-Class",
    "image": null,
    "price": "$5183.87",
    "stock": 1,
    "featured": false,
    "active": true
  }, {
    "id": 5,
    "catId": "3D73M4HL7BG139344",
    "name": "Subaru",
    "description": "Legacy",
    "image": null,
    "price": "$5780.13",
    "stock": 2,
    "featured": false,
    "active": false
  }, {
    "id": 6,
    "catId": "1G4CW54KX14969296",
    "name": "Toyota",
    "description": "Celica",
    "image": null,
    "price": "$8312.35",
    "stock": 1,
    "featured": true,
    "active": false
  }, {
    "id": 7,
    "catId": "JTDBT4K37B1331010",
    "name": "Ford",
    "description": "Fusion",
    "image": null,
    "price": "$4565.55",
    "stock": 4,
    "featured": true,
    "active": true
  }, {
    "id": 8,
    "catId": "19UUB3F56FA952442",
    "name": "Ford",
    "description": "Bronco",
    "image": null,
    "price": "$5870.24",
    "stock": 2,
    "featured": true,
    "active": false
  }, {
    "id": 9,
    "catId": "WBA3B9C57FF452517",
    "name": "Ford",
    "description": "Escort",
    "image": null,
    "price": "$4326.40",
    "stock": 4,
    "featured": true,
    "active": false
  }, {
    "id": 10,
    "catId": "2G4WC532751452420",
    "name": "Ford",
    "description": "F-Series",
    "image": null,
    "price": "$5892.99",
    "stock": 3,
    "featured": true,
    "active": false
  }, {
    "id": 11,
    "catId": "5TDBK3EH7DS605414",
    "name": "Lexus",
    "description": "RX Hybrid",
    "image": null,
    "price": "$5639.32",
    "stock": 1,
    "featured": true,
    "active": true
  }, {
    "id": 12,
    "catId": "1G4GB5GR9CF337029",
    "name": "Land Rover",
    "description": "Defender 110",
    "image": null,
    "price": "$4306.90",
    "stock": 1,
    "featured": false,
    "active": true
  }, {
    "id": 13,
    "catId": "WBAEV53465K934191",
    "name": "Ford",
    "description": "F250",
    "image": null,
    "price": "$7468.42",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 14,
    "catId": "WAUEH98E38A115794",
    "name": "Ford",
    "description": "EXP",
    "image": null,
    "price": "$7164.26",
    "stock": 1,
    "featured": true,
    "active": true
  }, {
    "id": 15,
    "catId": "1C3CCBCG3EN574065",
    "name": "Acura",
    "description": "Vigor",
    "image": null,
    "price": "$4495.51",
    "stock": 3,
    "featured": true,
    "active": true
  }, {
    "id": 16,
    "catId": "WP0CA2A81BS308070",
    "name": "Mitsubishi",
    "description": "Galant",
    "image": null,
    "price": "$5417.73",
    "stock": 2,
    "featured": false,
    "active": false
  }, {
    "id": 17,
    "catId": "KMHHT6KD8EU949952",
    "name": "Hyundai",
    "description": "Sonata",
    "image": null,
    "price": "$7977.57",
    "stock": 5,
    "featured": false,
    "active": false
  }, {
    "id": 18,
    "catId": "WVGAV7AX9AW454266",
    "name": "Toyota",
    "description": "Sienna",
    "image": null,
    "price": "$5430.52",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 19,
    "catId": "2G61N5S31F9951643",
    "name": "Mercury",
    "description": "Topaz",
    "image": null,
    "price": "$4325.64",
    "stock": 3,
    "featured": false,
    "active": false
  }, {
    "id": 20,
    "catId": "1G4HP57266U348353",
    "name": "GMC",
    "description": "Savana",
    "image": null,
    "price": "$6295.92",
    "stock": 3,
    "featured": true,
    "active": false
  }, {
    "id": 21,
    "catId": "KMHCM3AC2AU209225",
    "name": "Bentley",
    "description": "Continental",
    "image": null,
    "price": "$8646.79",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 22,
    "catId": "1G6AJ5S38D0907951",
    "name": "Toyota",
    "description": "Xtra",
    "image": null,
    "price": "$6024.99",
    "stock": 5,
    "featured": true,
    "active": true
  }, {
    "id": 23,
    "catId": "WDDGF4HB2EG486647",
    "name": "Chevrolet",
    "description": "HHR",
    "image": null,
    "price": "$5849.04",
    "stock": 4,
    "featured": true,
    "active": true
  }, {
    "id": 24,
    "catId": "WA1YD54B02N196926",
    "name": "Lincoln",
    "description": "Mark LT",
    "image": null,
    "price": "$7557.37",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 25,
    "catId": "5N1CR2MM6EC201592",
    "name": "Kia",
    "description": "Rondo",
    "image": null,
    "price": "$7328.99",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 26,
    "catId": "3LNDL2L33CR629536",
    "name": "Porsche",
    "description": "Boxster",
    "image": null,
    "price": "$5178.15",
    "stock": 2,
    "featured": true,
    "active": true
  }, {
    "id": 27,
    "catId": "4T1BF3EK0AU450000",
    "name": "GMC",
    "description": "Sonoma Club",
    "image": null,
    "price": "$7899.65",
    "stock": 1,
    "featured": true,
    "active": true
  }, {
    "id": 28,
    "catId": "JH4NA12681T453775",
    "name": "Mercury",
    "description": "Sable",
    "image": null,
    "price": "$8405.19",
    "stock": 2,
    "featured": false,
    "active": false
  }, {
    "id": 29,
    "catId": "3D73M4CL3AG765575",
    "name": "Lotus",
    "description": "Elise",
    "image": null,
    "price": "$4101.31",
    "stock": 6,
    "featured": false,
    "active": false
  }, {
    "id": 30,
    "catId": "WAUKD98P86A509885",
    "name": "Infiniti",
    "description": "QX56",
    "image": null,
    "price": "$5769.75",
    "stock": 6,
    "featured": true,
    "active": true
  }, {
    "id": 31,
    "catId": "WBA3N3C50FK928926",
    "name": "Chevrolet",
    "description": "Lumina",
    "image": null,
    "price": "$6098.48",
    "stock": 5,
    "featured": true,
    "active": true
  }, {
    "id": 32,
    "catId": "19UUA8F56DA853486",
    "name": "Dodge",
    "description": "Magnum",
    "image": null,
    "price": "$7304.70",
    "stock": 5,
    "featured": false,
    "active": false
  }, {
    "id": 33,
    "catId": "3C4PDCAB1DT856369",
    "name": "Mazda",
    "description": "Familia",
    "image": null,
    "price": "$8491.20",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 34,
    "catId": "1G6DP57V390038253",
    "name": "GMC",
    "description": "Yukon XL 1500",
    "image": null,
    "price": "$5875.37",
    "stock": 6,
    "featured": true,
    "active": true
  }, {
    "id": 35,
    "catId": "SAJWA4EC8FM279816",
    "name": "Saab",
    "description": "9-3",
    "image": null,
    "price": "$5200.86",
    "stock": 1,
    "featured": false,
    "active": true
  }, {
    "id": 36,
    "catId": "1C3CC5FB7AN289879",
    "name": "Volkswagen",
    "description": "Jetta III",
    "image": null,
    "price": "$7336.35",
    "stock": 5,
    "featured": true,
    "active": true
  }, {
    "id": 37,
    "catId": "SCFEFBAC0AG940074",
    "name": "Toyota",
    "description": "Land Cruiser",
    "image": null,
    "price": "$7622.10",
    "stock": 1,
    "featured": false,
    "active": false
  }, {
    "id": 38,
    "catId": "2B3CK8CT8AH395359",
    "name": "Ford",
    "description": "E-Series",
    "image": null,
    "price": "$4761.38",
    "stock": 3,
    "featured": true,
    "active": true
  }, {
    "id": 39,
    "catId": "KNAGM4AD6D5639999",
    "name": "Ford",
    "description": "Taurus",
    "image": null,
    "price": "$7736.82",
    "stock": 5,
    "featured": true,
    "active": false
  }, {
    "id": 40,
    "catId": "WAUGL98E98A129884",
    "name": "Subaru",
    "description": "SVX",
    "image": null,
    "price": "$5128.02",
    "stock": 4,
    "featured": false,
    "active": true
  }, {
    "id": 41,
    "catId": "KNADH5A37B6534920",
    "name": "Audi",
    "description": "Coupe GT",
    "image": null,
    "price": "$6877.91",
    "stock": 5,
    "featured": false,
    "active": false
  }, {
    "id": 42,
    "catId": "1G6DK5EV5A0973537",
    "name": "Scion",
    "description": "tC",
    "image": null,
    "price": "$7160.94",
    "stock": 3,
    "featured": false,
    "active": true
  }, {
    "id": 43,
    "catId": "WA1CFBFP0CA166863",
    "name": "Lamborghini",
    "description": "Gallardo",
    "image": null,
    "price": "$7937.14",
    "stock": 5,
    "featured": false,
    "active": false
  }, {
    "id": 44,
    "catId": "JTDKN3DP4C3185658",
    "name": "Chrysler",
    "description": "Town & Country",
    "image": null,
    "price": "$7077.40",
    "stock": 4,
    "featured": false,
    "active": false
  }, {
    "id": 45,
    "catId": "1FTSF3B54AE865458",
    "name": "Jeep",
    "description": "Wrangler",
    "image": null,
    "price": "$5639.57",
    "stock": 3,
    "featured": true,
    "active": false
  }, {
    "id": 46,
    "catId": "WAUFEBFM9BA623953",
    "name": "Lincoln",
    "description": "Town Car",
    "image": null,
    "price": "$5529.73",
    "stock": 3,
    "featured": true,
    "active": true
  }, {
    "id": 47,
    "catId": "KMHD35LH8FU374537",
    "name": "Toyota",
    "description": "Celica",
    "image": null,
    "price": "$5769.48",
    "stock": 3,
    "featured": true,
    "active": false
  }, {
    "id": 48,
    "catId": "WAUDT48H25K098578",
    "name": "Ford",
    "description": "Windstar",
    "image": null,
    "price": "$8997.02",
    "stock": 4,
    "featured": false,
    "active": true
  }, {
    "id": 49,
    "catId": "WUAAU34289N837734",
    "name": "Subaru",
    "description": "Outback",
    "image": null,
    "price": "$4533.05",
    "stock": 1,
    "featured": true,
    "active": true
  }, {
    "id": 50,
    "catId": "2HNYD28207H931316",
    "name": "Chevrolet",
    "description": "Cavalier",
    "image": null,
    "price": "$5104.65",
    "stock": 1,
    "featured": false,
    "active": false
  },]

  constructor() { }
}
